apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-radio-secret
  labels:
    {{- template "radio.labels" . }}
type: Opaque
data:
  {{- range $key, $val := .Values.config.secrets }}
  {{ $key }}: {{ tpl $val $ | b64enc | quote }}
  {{- end -}}