---
- name: Install dependences
  apt:
    name:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - python3-pip
    state: present
        
- name: Add gpg docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
        
- name: Add repository
  apt_repository:
    repo: deb [arch={{ go_arch }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }} stable
    state: present

- name: Install docker
  apt:
    name:
    - docker-ce
    state: present

- name: Install dependences in pip
  pip:
    name:
    - setuptools==59.6.0
    - docker==5.0.0
    - jsondiff==1.3.0
    - pyyaml==5.3.1
    - docker-compose==1.29.2
    state: latest

- name: enable docker
  service: 
    name: docker
    state: started
    enabled: true
